GET http://localhost:5000/api/v1/user/getAllUsers
###
GET http://localhost:5000/api/v1/product/getAllProducts
###
GET http://localhost:5000/api/v1/product/getAllBrands
###
GET http://localhost:5000/api/v1/product/searchWithBrand/Phy/Enfamil
###
GET http://localhost:5000/api/v1/product/getAllProductCategory
###
GET http://localhost:5000/api/v1/product/searchWithProductCategory/Phy/Sữa cho mẹ bầu
###
GET http://localhost:5000/api/v1/product/searchWithPrice/Phy/0/400999
###
GET http://localhost:5000/api/v1/product/searchWithName/phy
###
GET http://localhost:5000/api/v1/product/getInfoProductsDetail
###
POST http://localhost:5000/api/v1/product/createProduct
Content-Type: application/json

{
    "ProductName": "Enfamil NeuroPro",
    "Description": "Infant formula with MFGM and DHA",
    "Price": "540000",
    "StockQuantity": "800",
    "Image": "enfamil_neuropro.jpg",
    "ExpirationDate": "2025-12-31",
    "ManufacturingDate": "2024-01-01",
    "BrandName": "Enfamil",
    "ProductCategoryName": "Sữa cho em bé",
    "Status": "Deleted"
}
###
PUT http://localhost:5000/api/v1/product/editProduct/SE0002
Content-Type: application/json

{
    "ProductName": "Enfamil NeuroPro",
    "Description": "Infant formula with MFGM and DHA",
    "Price": "540000",
    "StockQuantity": "0",
    "Image": "enfamil_neuropro.jpg",
    "ExpirationDate": "2025-12-31",
    "ManufacturingDate": "2024-01-01",
    "BrandName": "Enfamil",
    "ProductCategoryName": "Sữa cho em bé"
}
###
PUT http://localhost:5000/api/v1/product/deleteProduct/SE0002
###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "UserName": "Nhan",
    "PhoneNumber": "0987654321",
    "Password": "1"
    //"RoleID": 2
}
###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "PhoneNumber": "0987654321",
    "Password": "12"
}
###
POST http://localhost:5000/api/v1/auth/logout
