GET http://localhost:5000/api/v1/user/getAllUsers
###
GET http://localhost:5000/api/v1/product/getAllProducts
###
GET http://localhost:5000/api/v1/product/getAllBrands
###
GET http://localhost:5000/api/v1/product/searchWithBrand/Phy/Enfamil
###
GET http://localhost:5000/api/v1/product/getAllProductCategory
###
GET http://localhost:5000/api/v1/product/searchWithProductCategory/phy/Sữa cho mẹ bầu
###
GET http://localhost:5000/api/v1/product/searchWithPrice/Phy/0/10000000
###
GET http://localhost:5000/api/v1/product/searchWithName/phy
###
GET http://localhost:5000/api/v1/product/getInfoProductsDetail
###
POST http://localhost:5000/api/v1/product/createProduct
Content-Type: application/json

{
    "ProductName": "Enfamil NeuroPro",
    "Description": "Infant formula with MFGM and DHA",
    "Price": "540000",
    "StockQuantity": "800",
    "Image": "enfamil_neuropro.jpg",
    "ExpirationDate": "2025-12-31",
    "ManufacturingDate": "2024-01-01",
    "BrandName": "Enfamil",
    "ProductCategoryName": "Sữa cho em bé",
    "Status": "Deleted"
}
###
PUT http://localhost:5000/api/v1/product/editProduct/SE0002
Content-Type: application/json

{
    "ProductName": "Enfamil NeuroPro",
    "Description": "Infant formula with MFGM and DHA",
    "Price": "540000",
    "StockQuantity": "0",
    "Image": "enfamil_neuropro.jpg",
    "ExpirationDate": "2025-12-31",
    "ManufacturingDate": "2024-01-01",
    "BrandName": "Enfamil",
    "ProductCategoryName": "Sữa cho em bé"
}
###
PUT http://localhost:5000/api/v1/product/deleteProduct/SE0002
###
GET http://localhost:5000/api/v1/product/getProductInfoByID/SE0009
###
GET http://localhost:5000/api/v1/product/get5ProductsLowestFinalPrice/
###
GET http://localhost:5000/api/v1/product/getTop6MilksForPregnantMother/
###
GET http://localhost:5000/api/v1/product/getTop6MilkForBaby/
###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "UserName": "Nhan",
    "PhoneNumber": "84933802522",
    "Password": "1"
}
###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "PhoneNumber": "84933802522",
    "Password": "1"
}
###
POST http://localhost:5000/api/v1/auth/logout
###
GET http://localhost:5000/api/v1/comment/getAllComments
###
GET http://localhost:5000/api/v1/comment/getUnansweredComments
###
POST http://localhost:5000/api/v1/comment/repComment/6
Content-Type: application/json

{
    "Rep": "Cảm ơn bạn"
}
###
GET http://localhost:5000/api/v1/auth/google
###
POST  http://localhost:5000/api/v1/payment/create_payment_url
Content-Type: application/json

{
    "orderID": 21,
    "amount": 100000,
    "language": "vn"
}
// Ngân hàng: NCB
// Số thẻ: 9704198526191432198
// Tên chủ thẻ: NGUYEN VAN A
// Ngày phát hành: 07/15
// OTP: 123456

###
POST https://sandbox.vnpayment.vn/qrpayauth/api/merchant/get_bank_list
Content-Type: application/x-www-form-urlencoded

tmn_code=8VGHK1JI
###
GET http://localhost:5000/api/v1/article/getAllArticles/
###
GEt http://localhost:5000/api/v1/article/getArticlesByID/M0000001/
###
GEt http://localhost:5000/api/v1/article/getArticlesByContent/Tin tức/
###
GET http://localhost:5000/api/v1/article/getAllArticleCategory/
###
POST http://localhost:5000/api/v1/article/createArticle/
Content-Type: application/json

{
    "Title": "Chất lượng sữa mẹ theo thời gian có gì thay đổi?",
    "HeaderImage": "image5.png",
    "Content": "Sữa cho mẹ bầu",
    "PublishDate": "2021-05-16",
    "AuthorID": "M0000001",
    "ArticleCategoryID": 1
}
###
PUT http://localhost:5000/api/v1/article/deleteArticle/20
###
PUT http://localhost:5000/api/v1/article/editArticle/14
Content-Type: application/json

{
    "Title": "Chất lượng sữa mẹ theo thời gian có gì thay đổi?",
    "HeaderImage": "image5.png",
    "Content": "Tin tức",
    "PublishDate": "2021-05-16",
    "AuthorID": "M0000001",
    "ArticleCategoryID": 2
}

###
GET http://localhost:5000/api/v1/user/getAllUsers/
###
PUT http://localhost:5000/api/v1/user/editUser/M0000001/
Content-Type: application/json

{
    "RoleID": "2"
}
###
GET http://localhost:5000/api/v1/user/getUserByRoleID/3/
###
PUT http://localhost:5000/api/v1/user/disableUser/M0000002/
Content-Type: application/json

{
    "Status": "False"
}


